# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from .._models import BaseModel
from .image_gen_input_usage_details import ImageGenInputUsageDetails

__all__ = ["ImageGenUsage"]


class ImageGenUsage(BaseModel):
    input_tokens: int
    """The number of tokens (images and text) in the input prompt."""

    input_tokens_details: ImageGenInputUsageDetails
    """The input tokens detailed information for the image generation."""

    output_tokens: int
    """The number of output tokens generated by the model."""

    total_tokens: int
    """The total number of tokens (images and text) used for the image generation."""
