# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

from .._models import BaseModel
from .local_shell_exec_action import LocalShellExecAction

__all__ = ["LocalShellToolCall"]


class LocalShellToolCall(BaseModel):
    id: str
    """The unique ID of the local shell call."""

    action: LocalShellExecAction
    """Execute a shell command on the server."""

    call_id: str
    """The unique ID of the local shell tool call generated by the model."""

    status: Literal["in_progress", "completed", "incomplete"]
    """The status of the local shell call."""

    type: Literal["local_shell_call"]
    """The type of the local shell call. Always `local_shell_call`."""
